/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AccountingApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AccountingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MySecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}